version: 2

models:
  - name: dim_listings_cleansed
    description: "test for listings"
    columns:
      - name: listing_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

